language: node_js
node_js:
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'
- '10.6.0'

sudo: false

# The default (implicit) Travis stage "test" runs for all versions of Node.js
# listed above. It runs "npm test" as its script command by default.
# All other stages (greenkepper lockfile and deployment via semantic-release)
# are only run for one specific Node.js version.

# Do not build tags on Travis. Tags are added by semantic-release in a previous
# build, so the additional build is redundant, since it would only run the same
# verification that ran before adding the tag.
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"

# Define order of stages and restrict semantic-release to only run on master:
stages:
  - test
  - greenkeeper
  - name: semantic-release
    if: env(TRAVIS_PULL_REQUEST) = false AND branch = master

# Define the custom build stages (greenkeeper lockfile update and semantic
# release):
jobs:
  include:
    - stage: greenkeeper
      node_js: '10.6.0'
      install: npm install
      before_script: npm install --global greenkeeper-lockfile
      script: greenkeeper-lockfile-update
      deploy:
        provider: script
        skip_cleanup: true
        script: greenkeeper-lockfile-upload

    - stage: semantic-release
      node_js: '10.6.0'
      script: skip
      before_deploy: npm install @semantic-release/changelog @semantic-release/git --no-save
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release

env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
  - secure: mZrVnTc5Jm8ykinjZb6cx3g0eQly002JN7pmWXuEO7M9T5NQzdIsJbl629NoCfy/b863i4mJJ9ZJYvB1wOaw/+dUp0IRor2KI3UJi8kSB9q4h2xVo3H/oIM0lVGftQmFFNJcojNPNHjhHVY9qBnF/20B/ydh+lQHQxChAA/WixU=
